<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="hettps://www.ros.org/wiki/xacro">

    <!-- Cores -->
    <material name="green">
        <color rgba="0.0 0.5 0.0 1"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 0.5 1"/>
    </material>
    <material name="red">
        <color rgba="0.5 0.0 0.0 1"/>
    </material>
    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <!--  VariÃ¡veis  -->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_heigh" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    
    <link name="base_footprint_link"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_heigh}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <!--collision>
            <geometry>
                
            </geometry>
        </collision-->
    </link>

    <joint name="base_joint" type="fixrd">
        <parent link="base_footprint_link"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <material name="gray"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left" />
    
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="right" />

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${- (base_width + wheel_length) / 2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${-base_length / 3.0} 0.0 ${- wheel_radius / 2.0}" rpy="0.0 0.0 0.0"/>
    </joint>

</robot>
